spring.application.name=api
spring.ai.openai.api-key=${OPENAI_API_KEY:your_api_key_here}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-flash-latest
server.port=${PORT:8080}
